using EMSCA.Domain.Common;

namespace EMSCA.Domain.Entities
{
    public partial class Accountdetail : BaseEntity { }
    public partial class Approval : BaseEntity { }
    public partial class ApprovalConfiguration : BaseEntity { }
    public partial class ApprovalConfigurationDetail : BaseEntity { }
    public partial class ApprovalDetail : BaseEntity { }
    public partial class Area : BaseEntity { }
    public partial class City : BaseEntity { }
    public partial class Company : BaseEntity { }
    public partial class Country : BaseEntity { }
    public partial class Customer : BaseEntity { }
    public partial class CustomerBillingDetail : BaseEntity { }
    public partial class Department : BaseEntity { }
    public partial class Documentdetail : BaseEntity { }
    public partial class Driver : BaseEntity { }
    public partial class Employee : BaseEntity { }
    public partial class EmployeeDocumentDetail : BaseEntity { }
    public partial class Event : BaseEntity { }
    public partial class EventCategory : BaseEntity { }
    public partial class EventDocumentDetail : BaseEntity { }
    public partial class EventEntry : BaseEntity { }
    public partial class EventEntryDetail : BaseEntity { }
    public partial class EventEntryLog : BaseEntity { }
    public partial class EventTermsCondition : BaseEntity { }
    public partial class Function : BaseEntity { }
    public partial class FunctionRoleMap : BaseEntity { }
    public partial class Gate : BaseEntity { }
    public partial class GateDetail : BaseEntity { }
    public partial class Instruction : BaseEntity { }
    public partial class LoginHistory : BaseEntity { }
    public partial class Material : BaseEntity { }
    public partial class MaterialCategory : BaseEntity { }
    public partial class MaterialSubCategory : BaseEntity { }
    public partial class MaterialType : BaseEntity { }
    public partial class Metadata : BaseEntity { }
    public partial class NumberingSchema : BaseEntity { }
    public partial class NumberingSchemaSearchView : BaseEntity { }
    public partial class Plant : BaseEntity { }
    public partial class Role : BaseEntity { }
    public partial class RoleWiseScreenMappingView : BaseEntity { }
    public partial class Route : BaseEntity { }
    public partial class Shift : BaseEntity { }
    public partial class State : BaseEntity { }
    public partial class Supplier : BaseEntity { }
    public partial class SupplierBillingdetail : BaseEntity { }
    public partial class SupplierType : BaseEntity { }
    public partial class User : BaseEntity { }
    public partial class UserBranchMap : BaseEntity { }
    public partial class UserCompanyMap : BaseEntity { }
    public partial class UserGateMap : BaseEntity { }
    public partial class UserPlantMap : BaseEntity { }
    public partial class UserPlantMapView : BaseEntity { }
    public partial class UserRoleMap : BaseEntity { }
    public partial class UserRoleMapView : BaseEntity { }
    public partial class UserRoleMappedFunctionView : BaseEntity { }
    public partial class UserScreenMapping : BaseEntity { }
    public partial class UserSession : BaseEntity { }
    public partial class UserVenueMap : BaseEntity { }
    public partial class UserVenueMapView : BaseEntity { }
    public partial class UserView : BaseEntity { }
    public partial class Vehicle : BaseEntity { }
    public partial class VehicleDocumentDetail : BaseEntity { }
    public partial class Vendor : BaseEntity { }
    public partial class Venue : BaseEntity { }
    public partial class VisitInformation : BaseEntity { }
    public partial class VisitInformationDetail : BaseEntity { }
    public partial class VisitLog : BaseEntity { }
    public partial class Visitor : BaseEntity { }
    public partial class VisitorDetail : BaseEntity { }
    public partial class VisitorEntry : BaseEntity { }
    public partial class VisitorEntryAtvDetail : BaseEntity { }
    public partial class VisitorEntryBelongingDetail : BaseEntity { }
    public partial class VisitorEntryDetail : BaseEntity { }
    public partial class VisitorEntryLog : BaseEntity { }
    public partial class VisitorEntryMaterialDetail : BaseEntity { }
    public partial class WhatsAppLog : BaseEntity { }
    public partial class WorkPermit : BaseEntity { }
    public partial class WpCompanyDoc : BaseEntity { }
    public partial class WpWorkerDetail : BaseEntity { }
    public partial class WpWorkerDoc : BaseEntity { }
}
